= Changelog
:toc:


All notable changes to this project will be documented in this file.

The format is based on https://keepachangelog.com/en/1.0.0/[Keep a Changelog],
and this project adheres to https://semver.org/spec/v2.0.0.html[Semantic Versioning].




== [0.0.2] - 2020-11-06

=== Changed

* Update the documentation.
Also, forgot some to-be documented stuff such as the `copyright` parameter for content frontmatter.


=== Removed

* `$POST.Params.hidden` has been removed in favor the http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/[build options].
Though, now this requires the module to be at Hugo v0.65.0 onwards.




== [0.0.1] - 2020-10-21

=== Added

* The CHANGELOG file even though this is overkill for such a small project.
* RSS feed template based on https://www.rssboard.org/rss-2-0-1[RSS v2.0.1 spec].
* Atom feed template based on https://tools.ietf.org/html/rfc4287[IETF RFC4287].
* JSON feed template as indicated from its https://www.jsonfeed.org/version/1.1[version 1.1 specifications].
* README covering most of the things needed to get a quick jump including installation with either the theme folder or Hugo modules, use cases, and references for future references.
* License the project under MIT open license.

